config/routes.rb
Aldo::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount ActiveAdmin::Tinymce::Engine => '/', as: 'admin_editor'


  root to: 'main#index'

  get 'contacts', to: 'main#contacts'
  get 'about', to: 'main#about'
  get 'about/biography', to: 'main#about_biography'

  get 'salon', to: 'main#salon'
  get 'salon/masters', to: 'main#salon_masters'
  get 'salon/interior', to: 'main#salon_interior'

  get 'press', to: 'main#press'

  get 'art', to: 'main#art'

  resources :news, only: [:index, :show]
  get 'news/offset/:offset', to: 'news#index_line'
  
  resources :services, only: [:index, :show]
  
  resource :appointment, only: [:show, :create]

  resources :brends, only: [:show] do
    resources :products, only: [:index, :show]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.is_a? AdminUser
      can :manage, :all
      cannot [:destroy, :create], Gallery
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :fio, :phone, :email, :service_id, :master_id
  belongs_to :service
  belongs_to :master

  validates :service, :fio, :phone, presence: true

  after_create do
    #AppointmentMailer.appointment_email(self).deliver
  end
end

app/models/brend.rb
class Brend < ActiveRecord::Base
  attr_accessible :name, :header, :text, :background

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :products

  has_attached_file :background
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :title, :images_attributes

  has_and_belongs_to_many :images

  accepts_nested_attributes_for :images, :allow_destroy => :true
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :path

  has_attached_file :path,
                    styles: {
                      thumb:["50x50", :png],
                      art: ["230x230#", :png],
                      news: ["247x247#", :png]
                    },
                    path: ':rails_root/public/system/images/:style/:filename',
                    url: '/system/images/:style/:filename'

  has_and_belongs_to_many :news
  has_and_belongs_to_many :galleries
end

app/models/master.rb
class Master < ActiveRecord::Base
  attr_accessible :fio, :photo, :biography, :service_ids

  has_attached_file :photo, :styles => { thumbnail: '50x50#', :art => "230x230#" }

  has_and_belongs_to_many :services
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :title, :body, :preview, :images_attributes

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :images

  accepts_nested_attributes_for :images, :allow_destroy => :true
end

app/models/press.rb
class Press < ActiveRecord::Base
  attr_accessible :title, :image, :document
  
  has_attached_file :document

  has_attached_file :image, :styles => { thumbnail: '50x50#', :art => "230x230#" }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :text, :background, :brend_id

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :brend

  has_attached_file :background
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :name, :description, :background

  has_and_belongs_to_many :masters

  has_attached_file :background

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :title, :content, :href, :background

  has_attached_file :background, :styles => { thumbnail: '50x50#', :background => "x390" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def show
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new params[:appointment]

    unless @appointment.save
      render 'show'
    end
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
  end

  def show
    gallery = GalleryArt.find params[:id]
    render locals: { gallery: gallery }
  end
end

app/controllers/brends_controller.rb
class BrendsController < ApplicationController
  def show
    @brend = Brend.find params[:id]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def contacts
  end

  def about
  end

  def about_biography
  end

  def salon
  end

  def salon_masters
  end

  def salon_interior
  end

  def press
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end

  def index_line
    render locals: { offset: Integer(params['offset']) }, layout: false
  end

  def show
    news_item = News.find params[:id]

    render locals: { news_item: news_item }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @brend = Brend.find params[:brend_id]
  end

  def show
    @product = Product.find params[:id]
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end

  def show
    @service = Service.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/galleries/_show.slim
#_background style="background-image: url(/images/background/common_bg.jpg); opacity: 1; display: block;"

.gallery
  - gallery.images.each do |image|
    a href=admin_image_path(image)
      img src=image.path.url(:art)
      .fade

app/views/admin/images/_images_new_form.html.erb
<div id="my_file_uploader"></div>
<script type="text/javascript">
    var uploader = new qq.FileUploader({
        element: document.getElementById('my_file_uploader'),
        action: '<%= add_files_admin_images_path %>',
        params: { "authenticity_token": "<%= form_authenticity_token %>" },
        customHeaders: { "X-File-Upload": "true" }
    });
</script>

app/views/admin/images/_modal.html.erb
<div id="modal" class="modal hide fade" tabindex="-1" data-width="760">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Link instellen</h3>
  </div>
  <div class="modal-body form-horizontal">
    Bla
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn">Annuleren</button>
    <button type="button" class="btn btn-primary">Opslaan</button>
  </div>
</div>

app/views/admin/masters/_master_form.html.haml
%form
  %fieldset.inputs
    %ol
      %li
        %label
          = t(:fio)
        %input#fio

app/views/admin/masters/_show.slim
#_background style="background-image: url(/images/background/common_bg.jpg); opacity: 1; display: block;"

.page.center
  .page-content
    ._master
      img._col src=master.photo.url(:art)
      ._master_description._col
        ._master_fio= master.fio
        ._master_biography= raw master.biography

app/views/admin/slides/_show.slim
#content
  .sliding-div style="background-image: url(#{slide.background.url(:background)});"
    .slide-background
    .slide-title= slide.title
    .slide-wrapper
      .slide-content= slide.content
      a._button target='_blank' href=slide.href Перейти в раздел

    .slide-shadow

app/views/brends/_line.slim
._production_line
  - Brend.all.each do |brend|
    a._button href=( brend.products.count == 0 ? brend_path(brend) : brend_products_path(brend) ) = brend.name

app/views/brends/show.slim
.ajok_data data={ back: (@brend.background.exists? ? @brend.background.url : false), menu: 5 }

.page.brend
  h1.grey Продукция

  = render "/brends/line"

  .marked= @brend.header

  div class='page-content semi-narrow semi-transparent' style="padding: 20px; text-transform: none; margin-bottom: 20px;" 
    = simple_format @brend.text

    = render partial: 'partials/sharebox'

app/views/news/_news.slim
.news-item.cf
  - if showing
    a._button href=news_index_path Назад

  .date= l(news_item.created_at, :format => '%e %B %Y')
  
  h2.marked= news_item.title

  .images.cf.yoxview
    - news_item.images.limit( showing ? nil : 3 ).each do |image|
      img src=image.path.url(:news)

  div= raw( ( showing ) ? news_item.body : news_item.preview )

  - if !showing
    a._button._button_150 href=news_path( news_item ) читать

app/views/news/index.slim
.ajok_data data={ back: '/images/background/News.jpeg', menu: 0 }

.page.center
  h1 Новости
  .page-content
    = render template: 'news/index_line', locals: { offset: 0 }

javascript:
  (function(){
    $('.page-content').on('mousedown', '#more', function(e){
      var q = $(this);

      if( !q.attr('href') ) return;

      $.get(
        q.attr('href'),
        function( data ){
          q.parent().remove();
          $('.page-content').append( data );
        }
      );

      q.removeAttr('href');

      q.fadeOut(500, function(){ q.next().show(); });

      return false;
    });
  })();

app/views/news/index_line.slim
- news = News.order('id DESC').limit( 10 ).offset( offset )

= render partial: "news/news", :collection => news, :as => 'news_item', locals: { showing: false }

- unless news.size < 10
  - if News.count > offset + 10
    .more
      a#more href="/news/offset/#{offset + 10}" Показать еще
      img.loading src="/images/loading.gif" alt="Загрузка"

app/views/news/show.slim
- content_for :meta
  meta property="og:type" content="article"
  meta property="og:title" content=news_item.title
  meta property="og:description" content=news_item.preview
  meta property="og:url" content=news_path( news_item )

  - if news_item.images.count > 0
    meta property="og:image" content=news_item.images.first.path.url(:art)

.ajok_data data={ back: '/images/background/News.jpeg' }

.page.center
  h1 Новости
  .page-content
    = render partial: "news/news", locals: { news_item: news_item, showing: true }

    = render partial: 'partials/sharebox'

app/views/products/index.slim
.ajok_data data={ back: (@brend.background.exists? ? @brend.background.url : false), menu: 5 }

.page
  h1.grey Продукция

  = render "/brends/line"

  .marked= @brend.header

  div
    ._button_list
      - @brend.products.all.each do |p|
        a._button href=brend_product_path( @brend, p ) = p.name

app/views/products/show.slim
.ajok_data data={ back: (@product.background.exists? ? @product.background.url : false) }

coffee:
  ajok_data = $ '.ajok_data'

  return unless ajok_data.data 'back'

  ajok_data.ajok_toggle ( x )->
    $('#_background').css
      backgroundSize: ( if x then 'contain' else '' )
      backgroundPosition: ( if x then 'right' else '' )
      backgroundColor: ( if x then 'black' else '' )

.page.item
  h1 Продукция
  .marked= @product.name

  a._button href=brend_products_path( @product.brend ) Назад

  .page-content.semi-transparent.narrow
    = simple_format @product.text

    = render partial: 'partials/sharebox'

app/views/services/index.slim
.ajok_data data={ back: '/images/background/Services.jpg', menu: 4 }

.page
  h1 Услуги
  .marked РАСКРОЙТЕ ТЫСЯЧИ ГРАНЕЙ ВАШЕЙ КРАСОТЫ <br> С УСЛУГАМИ ALDO COPPOLA

  div
    - Service.all.each_slice( (Service.count.round(2)*0.5).ceil ).each do |services_group|
      ._button_list
        - services_group.each do |s|
          a._button href=service_path(s) = s.name

app/views/services/show.slim
.ajok_data data={ back: @service.background.url }

.page.item
  h1 Услуги
  .marked= @service.name

  ._two_buttons
    a._button href=services_path Назад

    = link_to 'Записаться', appointment_path( s: @service.id ), class: '_button _get_it'

  .page-content.semi-transparent.narrow
    = simple_format @service.description

    = render partial: 'partials/sharebox'